create:
  name: adversarial_training_attack
  eps: [0.01, 0.1, 0.25]
  eps_step: 0.01
  max_iter: 40
  num_classes: 10

remove:
  name: adversarial_training_removal
  epochs: 5

dataset:
  name: CIFAR10DataLoader
  subset: attacker
  train: True
  download: False
  apply_augmentation: False
  root: ~/.wrt/data
  batch_size: 64
  image_size: 32
  num_workers: 2

true_labels: False
name: adversarial_training
output_dir: outputs/cifar10/attacks/adversarial_training/