create:
  name: adversarial_training_attack
  eps: [0.01, 0.1, 0.25]
  eps_step: 0.01
  max_iter: 40
  num_classes: 10

remove:
  name: adversarial_training_removal
  epochs: 60

surrogate_model:
  name: cifar_wide_resnet_features
  image_size: 32
  num_classes: 10

optimizer:
  name: SGD
  lr: 0.1
  momentum: 0.9
  weight_decay: 0.0005
  nesterov: True

scheduler:
  name: MultiStepLR
  milestones: [20, 35, 50]
  gamma: 0.2

dataset:
  name: CIFAR10DataLoader
  subset: all
  download: False
  apply_augmentation: True
  root: ~/.wrt/data
  batch_size: 64
  image_size: 32
  num_workers: 2

true_labels: False
name: adversarial_extraction
output_dir: outputs/cifar10/attacks/adversarial_extraction/