attack_list: [attack1, attack2, attack3]

create:
  name: stacked_attack

remove:
  name: stacked_attack_removal

dataset:
  name: CIFAR10DataLoader
  subset: attacker
  root: ~/.wrt/data
  batch_size: 32
  image_size: 32
  num_workers: 2

# This dataset is not used. True labels are only given to speed up runtime.
true_labels: True
name: stacked_attack3
output_dir: outputs/cifar10/attacks/combined_attack3/

attack1:
  create:
    name: weight_shifting_attack

  remove:
    name: weight_shifting_removal
    epochs: 10
    lmbda: 1.5
    check_every_n_batches: 200

  dataset:
    name: CIFAR10DataLoader
    subset: attacker
    download: False
    root: ~/.wrt/data
    batch_size: 64
    image_size: 32
    num_workers: 2

  true_labels: False
  name: weight_shifting
  output_dir: outputs/cifar10/attacks/weight_shifting/

attack2:
  create:
    name: input_flipping_attack
    num_classes: 10

  remove:
    name: input_flipping_removal

  dataset:
    name: CIFAR10DataLoader
    subset: attacker
    root: ~/.wrt/data
    batch_size: 64
    image_size: 32
    num_workers: 2

  true_labels: True
  name: input_flipping
  output_dir: outputs/cifar10/attacks/input_flipping/

attack3:
  create:
    name: input_gaussian_smoothing_attack
    num_classes: 10
    std: 0.5

  remove:
    name: input_gaussian_smoothing_removal

  dataset:
    name: CIFAR10DataLoader
    subset: attacker
    root: ~/.wrt/data
    download: False
    batch_size: 64
    image_size: 32
    num_workers: 2

  true_labels: True
  name: input_gaussian_smoothing
  output_dir: outputs/cifar10/attacks/input_gaussian_smoothing/

