create:
  name: ensemble_attack
  num_classes: 10

surrogate_model:
  name: cifar_wide_resnet_features
  image_size: 32
  num_classes: 10

remove:
  name: ensemble_removal
  epochs: 60
  splits: 3
  epsilon: 0.2

dataset:
  name: CIFAR10DataLoader
  subset: all
  root: ~/.wrt/data
  download: False
  batch_size: 64
  image_size: 32
  num_workers: 2

optimizer:
  name: SGD
  lr: 0.1
  momentum: 0.9
  weight_decay: 0.0005
  nesterov: True

scheduler:
  name: MultiStepLR
  milestones: [20, 35, 50]
  gamma: 0.2

true_labels: False
name: ensemble
output_dir: outputs/cifar10/attacks/ensemble/