create:
  name: feature_squeezing_attack
  num_classes: 10
  bit_depth: 4

remove:
  name: feature_squeezing_removal

dataset:
  name: CIFAR10DataLoader
  subset: attacker
  root: ~/.wrt/data
  download: False
  batch_size: 64
  image_size: 32
  num_workers: 2

true_labels: True
name: feature_squeezing
output_dir: outputs/cifar10/attacks/feature_squeezing/