create:
  name: ftal_attack
  num_classes: 10

remove:
  name: ftal_removal
  epochs: 5

dataset:
  name: CIFAR10DataLoader
  subset: attacker
  root: ~/.wrt/data
  batch_size: 64
  image_size: 32
  num_workers: 2

true_labels: True
name: ftal
output_dir: outputs/cifar10/attacks/ftal/