create:
  name: input_quantization_attack
  num_classes: 10
  num_divisions: 16

remove:
  name: input_quantization_removal

dataset:
  name: CIFAR10DataLoader
  subset: attacker
  root: ~/.wrt/data
  download: False
  batch_size: 64
  image_size: 32
  num_workers: 2

true_labels: True
name: input_quantization
output_dir: outputs/cifar10/attacks/input_quantization/