create:
  name: neural_cleanse_partial_pruning_attack
  extract: True
  num_classes: 10
  ratio: 0.1
  layer_name: layer3
  layer_index: 18
  extract_kwargs:
    extract_epochs: 4
    finetune_epochs: 8
    lmbda: 0.01
    batch_size: 64

remove:
  name: neural_cleanse_partial_pruning_removal
  epochs: 5

dataset:
  name: CIFAR10DataLoader
  subset: attacker
  root: ~/.wrt/data
  download: False
  batch_size: 64
  image_size: 32
  num_workers: 2

true_labels: False
name: neural_cleanse_partial_pruning
output_dir: outputs/cifar10/attacks/neural_cleanse_partial_pruning/