python main_extraction.py cfg/extraction/certified_resnet_cifar10_unrelated.yml
python main_extraction.py cfg/extraction/certified_resnet_cifar10_unrelated_multi.yml
python main_extraction.py cfg/extraction/certified_vit_cifar10_unrelated.yml
python main_extraction.py cfg/extraction/certified_vit_cifar10_unrelated_multi.yml