python main_extraction.py cfg/extraction/adi_resnet_cifar10_unrelated.yml
python main_extraction.py cfg/extraction/adi_resnet_cifar10_unrelated_multi.yml
python main_extraction.py cfg/extraction/adi_vit_cifar10_unrelated.yml
python main_extraction.py cfg/extraction/adi_vit_cifar10_unrelated_multi.yml