python main_ftal.py cfg/ftal/smalllr_mix/certified_resnet_cifar10_unrelated.yml
python main_ftal.py cfg/ftal/medlr_mix/certified_resnet_cifar10_unrelated.yml
python main_ftal.py cfg/ftal/biglr_mix/certified_resnet_cifar10_unrelated.yml
python main_ftal.py cfg/ftal/smalllr_mix/certified_resnet_cifar10_unrelated_multi.yml
python main_ftal.py cfg/ftal/medlr_mix/certified_resnet_cifar10_unrelated_multi.yml
python main_ftal.py cfg/ftal/biglr_mix/certified_resnet_cifar10_unrelated_multi.yml

python main_ftal.py cfg/ftal/smalllr_mix/certified_vit_cifar10_unrelated.yml
python main_ftal.py cfg/ftal/medlr_mix/certified_vit_cifar10_unrelated.yml
python main_ftal.py cfg/ftal/biglr_mix/certified_vit_cifar10_unrelated.yml
python main_ftal.py cfg/ftal/smalllr_mix/certified_vit_cifar10_unrelated_multi.yml
python main_ftal.py cfg/ftal/medlr_mix/certified_vit_cifar10_unrelated_multi.yml
python main_ftal.py cfg/ftal/biglr_mix/certified_vit_cifar10_unrelated_multi.yml