attack_list: [attack1, attack2]

create:
  name: stacked_attack

remove:
  name: stacked_attack_removal

dataset:
  name: ImageNetDataLoader
  subset: attacker
  root: ~/.wrt/data
  batch_size: 64
  image_size: 224
  num_workers: 16
  n_test: 1000

# This dataset is not used. True labels are only given to speed up runtime.
true_labels: True
name: combined_attack1
output_dir: outputs/imagenet/attacks/combined_attack1/

attack1:
  pretrained:
    jia: outputs/imagenet/attacks_d/transfer_learning/00013_transfer_learning_attack_wm_jia/best.pth
    blackmarks: outputs/imagenet/attacks_d/transfer_learning/00008_transfer_learning_attack_wm_blackmarks/checkpoint.pth

  create:
    name: transfer_learning_attack
    lr: 0.001
    freeze: False
    num_classes: 1000
    image_size: 224
    parent_shape: 299
    train_all_params_after_n_batches: 5000
    removed_layers: [ 'fc' ]
    preprocessor: imagenet
    layer_bounds: [ 72, 312, -1 ]
    layer_lrs: [ 0.00000001, 0.000001, 0.001 ]

  optimizer:
    name: SGD
    lr: 0.001
    momentum: 0.9
    weight_decay: 0.0001

  surrogate_model:
    name: resnet_pretrained_open_images
    freeze_first_n_layers: 312
    image_size: 299
    num_classes: 5000

  remove:
    name: transfer_learning_removal
    epochs: 7

  dataset:
    name: ImageNetDataLoader
    subset: all
    root: ~/.wrt/data
    batch_size: 32
    image_size: 224
    num_workers: 16

  scheduler2:
    name: ReduceLROnPlateau
    factor: 0.1
    patience: 2
    verbose: True

  scheduler:
    name: MultiStepLR
    milestones: [ 5 ]
    gamma: 0.1

  true_labels: False
  name: transfer_learning
  output_dir: outputs/imagenet/attacks/transfer_learning/

attack2:
  create:
    name: input_flipping_attack
    num_classes: 1000

  remove:
    name: input_flipping_removal

  dataset:
    name: ImageNetDataLoader
    subset: attacker
    root: ~/.wrt/data
    batch_size: 64
    image_size: 224
    num_workers: 16

  true_labels: True
  name: input_flipping
  output_dir: outputs/imagenet/attacks/input_flipping/




