attack_list: [attack1, attack2, attack3, attack4]

create:
  name: stacked_attack

remove:
  name: stacked_attack_removal

dataset:
  name: ImageNetDataLoader
  subset: attacker
  root: ~/.wrt/data
  batch_size: 64
  image_size: 224
  num_workers: 16

# This dataset is not used. True labels are only given to speed up runtime.
true_labels: True
name: combined_attack6
output_dir: outputs/imagenet/attacks/combined_attack6/

attack1:
  create:
    name: neural_laundering_attack
    extract: True
    dataset: imagenet
    num_classes: 1000
    n_samples: 50000  # Maximum number of samples to load (limited by RAM)
    dt: 0.2 # threshold to prune fully-connected neurons
    ct: 0.5 # threshold to prune convolutional layer neurons
    extract_kwargs: # params for reconstructing the trigger.
      source_classes: [ 3 ]
      target_classes: [ 4 ]
      extract_epochs: 30
      finetune_epochs: 15
      lmbda: 0.01
      batch_size: 64

  remove:
    name: neural_laundering_partial_removal
    boost_factor: 100
    epochs: 5

  subset_dataset:
    name: ImageNetDataLoader
    subset: attacker
    root: ~/.wrt/data
    batch_size: 64
    image_size: 224
    num_workers: 16
    class_labels: [ 3, 4 ]

  dataset:
    name: ImageNetDataLoader
    subset: attacker
    root: ~/.wrt/data
    batch_size: 64
    image_size: 224
    num_workers: 16

  true_labels: False
  name: neural_laundering
  output_dir: outputs/imagenet/attacks/neural_laundering

attack2:
  create:
    name: weight_shifting_attack

  remove:
    name: weight_shifting_removal
    epochs: 5
    lmbda: 1.2
    lmbda2: 0

  dataset:
    name: ImageNetDataLoader
    subset: attacker
    root: ~/.wrt/data
    batch_size: 64
    image_size: 224
    num_workers: 16
    n_train: 100000

  true_labels: False
  name: weight_shifting
  output_dir: outputs/imagenet/attacks/weight_shifting/

attack3:
  create:
    name: random_occlusion_attack
    num_classes: 1000

  remove:
    name: random_occlusion_removal
    epochs: 1
    repeats: 5
    boost_factor: 100         # Number of times each sample is repeated per epoch.
    check_every_n_batches: 200
    epsilon: 0.3

  dataset:
    name: ImageNetDataLoader
    subset: attacker
    root: ~/.wrt/data
    apply_augmentation: False
    batch_size: 64
    image_size: 224
    num_workers: 16

  subset_dataset:
    name: ImageNetDataLoader
    subset: attacker
    root: ~/.wrt/data
    class_labels: [ 3, 4 ]
    apply_augmentation: False
    apply_normalization: False
    batch_size: 64
    image_size: 224
    num_workers: 16

  true_labels: False
  name: random_occlusion4
  output_dir: outputs/imagenet/attacks/random_occlusion4/

attack4:
  create:
    name: input_flipping_attack
    num_classes: 1000

  remove:
    name: input_flipping_removal

  dataset:
    name: ImageNetDataLoader
    subset: attacker
    root: ~/.wrt/data
    batch_size: 64
    image_size: 224
    num_workers: 16

  true_labels: True
  name: input_flipping
  output_dir: outputs/imagenet/attacks/input_flipping/


