create:
  name: retraining_attack
  num_classes: 1000
  image_size: 224

remove:
  name: retraining_removal
  epochs: 60
  batch_size: 64

surrogate_model:
  name: ImageNetDenseNetModel
  num_classes: 1000
  image_size: 224

dataset:
  name: ImageNetDataLoader
  subset: all
  root: ~/.wrt/data
  batch_size: 64
  image_size: 224
  num_workers: 16

optimizer:
  name: SGD
  lr: 0.1
  weight_decay: 0.0001
  momentum: 0.9

scheduler:
  name: ReduceLROnPlateau
  factor: 0.1
  patience: 2
  verbose: True

true_labels: False
name: cross_architecture_retraining_attack
output_dir: outputs/imagenet/attacks/cross_architecture_retraining/