create:
  name: distillation_attack
  num_classes: 1000
  image_size: 224
  alpha: 1.0
  T: 3.0

surrogate_model:
  name: imagenet_resnet
  num_classes: 1000
  image_size: 224

remove:
  name: distillation_removal
  epochs: 60

dataset:
  name: ImageNetDataLoader
  subset: all
  root: ~/.wrt/data
  batch_size: 64
  image_size: 224
  num_workers: 16
  apply_softmax: False

optimizer:
  name: SGD
  lr: 0.1
  weight_decay: 0.0001
  momentum: 0.9

scheduler:
  name: ReduceLROnPlateau
  factor: 0.1
  patience: 2
  verbose: True

true_labels: False
name: distillation
output_dir: outputs/imagenet/attacks/distillation/