create:
  name: ftal_attack
  num_classes: 1000

remove:
  name: ftal_removal
  epochs: 2

dataset:
  name: ImageNetDataLoader
  subset: attacker
  root: ~/.wrt/data
  batch_size: 32
  image_size: 224
  num_workers: 16

true_labels: True
name: ftal
output_dir: outputs/imagenet/attacks/ftal/