create:
  name: input_quantization_attack
  num_classes: 1000
  num_divisions: 16

remove:
  name: input_quantization_removal

dataset:
  name: ImageNetDataLoader
  subset: attacker
  root: ~/.wrt/data
  batch_size: 64
  image_size: 224
  num_workers: 16

# Dataset is unused, so we can set 'true_labels' to true.
true_labels: True
name: input_quantization
output_dir: outputs/imagenet/attacks/input_quantization/