create:
  name: label_noising_attack
  num_classes: 1000

remove:
  name: label_noising_removal
  epochs: 1
  epsilon: 0.99
  check_every_n_batches: 200

dataset:
  name: ImageNetDataLoader
  subset: attacker
  root: ~/.wrt/data
  batch_size: 64
  image_size: 224
  num_workers: 16
  n_train: 100000
  n_test: 1000
  top_k: 1

true_labels: True
name: label_noising1
output_dir: outputs/imagenet/attacks/label_noising1/