create:
  name: neural_laundering_attack
  extract: True
  dataset: imagenet
  num_classes: 1000
  n_samples: 50000  # Maximum number of samples to load (limited by RAM)
  dt: 0.2 # threshold to prune fully-connected neurons
  ct: 0.5 # threshold to prune convolutional layer neurons
  extract_kwargs: # params for reconstructing the trigger.
    source_classes: [ 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18 ]
    target_classes: [ 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18 ]
    extract_epochs: 80
    finetune_epochs: 25
    lmbda: 0.03
    batch_size: 64

remove:
  name: neural_laundering_partial_removal
  boost_factor: 100
  epochs: 5

subset_dataset:
  name: ImageNetDataLoader
  subset: attacker
  root: ~/.wrt/data
  batch_size: 64
  image_size: 224
  num_workers: 16
  class_labels: [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18]

dataset:
  name: ImageNetDataLoader
  subset: attacker
  root: ~/.wrt/data
  batch_size: 64
  image_size: 224
  num_workers: 16

true_labels: False
name: neural_laundering3
output_dir: outputs/imagenet/attacks/neural_laundering3