create:
  name: weight_shifting_attack

remove:
  name: weight_shifting_removal
  epochs: 5
  lmbda: 2.5
  lmbda2: 0
  epsilon: 0.8

dataset:
  name: ImageNetDataLoader
  subset: attacker
  root: ~/.wrt/data
  batch_size: 64
  image_size: 224
  num_workers: 16
  n_test: 1000

true_labels: True
name: weight_shifting5
output_dir: outputs/imagenet/attacks/weight_shifting5/