create:
  name: weight_quantization_attack

remove:
  name: weight_quantization_removal
  epochs: 5
  bits: 6
  epsilon: 0.7

dataset:
  name: ImageNetDataLoader
  subset: attacker
  root: ~/.wrt/data
  batch_size: 32
  image_size: 224
  num_workers: 16

true_labels: False
name: weight_quantization4
output_dir: outputs/imagenet/attacks/weight_quantization4/