create:
  name: weight_pruning_attack
  sparsity: 0.02

remove:
  name: weight_pruning_removal

dataset:
  name: ImageNetDataLoader
  subset: attacker
  root: ~/.wrt/data
  batch_size: 64
  image_size: 224
  num_workers: 16

# Dataset is unused, so we can set 'true_labels' to true.
true_labels: True
name: weight_pruning1
output_dir: outputs/imagenet/attacks/weight_pruning1/