create:
  name: weight_quantization_attack

remove:
  name: weight_quantization_removal
  epochs: 1
  bits: 6

dataset:
  name: ImageNetDataLoader
  subset: attacker
  root: ~/.wrt/data
  batch_size: 32
  image_size: 224
  num_workers: 16
  top_k: 1

true_labels: False
name: weight_quantization3
output_dir: outputs/imagenet/attacks/weight_quantization3/