wm_scheme:
  name: wm_adi
  num_classes: 1000

embed:
  name: wm_adi_embed
  boost_factor: 1000
  keylength: 100
  epochs: 5
  patience: 5
  check_every_n_batches: 200

source_model:
  name: imagenet_resnet
  image_size: 224
  num_classes: 1000

optimizer:
  name: SGD
  lr: 0.1
  weight_decay: 5.e-4
  momentum: 0.9
  nesterov: true

wm_dataset:
  name: AdiTriggerDataLoader
  root: ~/.wrt/data
  batch_size: 64
  image_size: 224
  num_workers: 16

dataset:
  name: ImageNetDataLoader
  subset: defender
  root: ~/.wrt/data
  batch_size: 64
  image_size: 224
  num_workers: 16

name: adi
output_dir: outputs/imagenet/wm/adi/


