wm_scheme:
  name: wm_blackmarks
  lmbda: 0.5
  eps: 0.5
  num_variants: 1
  num_classes: 1000
  compute_new_encoding: True

embed:
  name: wm_blackmarks_embed
  epochs: 5
  finetune_batches: 500
  keylength: 100
  key_expansion_factor: 100
  log_wm_acc_after_n_batches: 200
  patience: 2
  min_val: 1.0

source_model:
  name: imagenet_resnet
  image_size: 224
  num_classes: 1000

optimizer:
  name: SGD
  lr: 0.1
  weight_decay: 5.e-4
  momentum: 0.9
  nesterov: true

wm_dataset_alternative:
  name: ImageNetDataLoader
  apply_normalization: False
  apply_augmentation: False
  subset: defender
  train: True
  root: ~/.wrt/data
  batch_size: 64
  image_size: 224
  num_workers: 16

wm_dataset:
  name: FlatImagesDataLoader
  apply_normalization: False
  apply_augmentation: False
  subset: all
  root: ~/.wrt/data/ILSVRC/Data/CLS-LOC/test
  batch_size: 64
  image_size: 224
  num_workers: 16

dataset:
  name: ImageNetDataLoader
  subset: defender
  root: ~/.wrt/data
  n_test: 1000
  batch_size: 64
  image_size: 224
  num_workers: 16

wm_data_requires_labels: True
name: blackmarks
output_dir: outputs/imagenet/wm/blackmarks/


