wm_scheme:
  name: wm_dawn
  rate: 0.05
  num_classes: 1000

embed:
  name: wm_dawn_embed
  epochs: 60
  keylength: 100

source_model:
  name: imagenet_resnet
  num_classes: 1000
  image_size: 224

optimizer:
  name: SGD
  lr: 0.1
  weight_decay: 0.0001
  momentum: 0.9

scheduler:
  name: ReduceLROnPlateau
  factor: 0.1
  patience: 2
  verbose: True

surrogate_model:
  name: imagenet_resnet
  num_classes: 1000
  image_size: 224

surrogate_optimizer:
  name: SGD
  lr: 0.1
  weight_decay: 5.e-4
  momentum: 0.9
  nesterov: true

dataset:
  name: ImageNetDataLoader
  subset: all
  root: ~/.wrt/data
  batch_size: 64
  image_size: 224
  num_workers: 16

name: dawn
output_dir: outputs/imagenet/wm/dawn