wm_scheme:
  name: wm_deepmarks
  layer_index: 0
  gamma: 1
  num_classes: 1000

embed:
  name: wm_deepmarks_embed
  epochs: 5
  keylength: 100
  check_every_n_batches: 200
  patience: 5

source_model:
  name: imagenet_resnet
  image_size: 224
  num_classes: 1000

optimizer:
  name: SGD
  lr: 0.1
  weight_decay: 5.e-4
  momentum: 0.9
  nesterov: true

dataset:
  name: ImageNetDataLoader
  subset: defender
  root: ~/.wrt/data
  batch_size: 64
  image_size: 224
  num_workers: 16
  n_test: 5000

name: deepmarks
output_dir: outputs/imagenet/wm/deepmarks/


