wm_scheme:
  name: wm_blackmarks
  lmbda: 0.5
  eps: 0.5
  num_classes: 1000
  dataset_name: imagenet

source_model_architecture:
  name: imagenet_resnet
  image_size: 224
  num_classes: 1000

secret_keys:
  name: wm_blackmarks_keygen
  image_size: 224
  num_classes: 1000

null_models:
  name: load_null_models_imagenet

null_model_architecture:
  help: Determined at runtime

optimizer:
  name: SGD
  lr: 0.1
  weight_decay: 5.e-4
  momentum: 0.9
  nesterov: true

wm_dataset_old:
  name: ImageNetDataLoader
  subset: all
  apply_normalization: False
  apply_augmentation: False
  root: ~/.wrt/data
  train: False
  batch_size: 64
  image_size: 224
  num_workers: 16

wm_dataset:
  name: FlatImagesDataLoader
  apply_normalization: False
  apply_augmentation: False
  subset: all
  root: ~/.wrt/data/ILSVRC/Data/CLS-LOC/test
  batch_size: 64
  image_size: 224
  num_workers: 16

dataset:
  name: ImageNetDataLoader
  subset: defender
  root: ~/.wrt/data
  n_test: 5000
  batch_size: 64
  image_size: 224
  num_workers: 16

name: blackmarks
output_dir: outputs/imagenet/decision_thresholds/blackmarks