wm_scheme:
  name: wm_dawn
  rate: 0.5
  num_classes: 1000

secret_keys:
  name: wm_dawn_keygen
  num_classes: 1000
  image_size: 224

source_model_architecture:
  name: imagenet_resnet
  image_size: 224
  num_classes: 1000

null_models:
  name: load_null_models_imagenet

null_model_architecture:
  help: Nothing

optimizer:
  name: SGD
  lr: 0.1
  weight_decay: 5.e-4
  momentum: 0.9
  nesterov: true

dataset:
  name: ImageNetDataLoader
  subset: all
  root: ~/.wrt/data
  batch_size: 64
  image_size: 224
  num_workers: 16

name: dawn
output_dir: outputs/imagenet/decision_thresholds/dawn