wm_scheme:
  name: wm_deepsignwb
  layer_dim: 25088
  layer_index: 62
  gamma0: 1
  gamma1: 0.01
  gamma2: 3
  gamma3: 0
  embedding_rate: 5
  mu_lr: .01
  num_gaussians: 1
  from_scratch: False
  separate_means: False
  num_classes: 1000

secret_keys:
  name: wm_deepsignwb_keygen
  batch_size: 64
  image_size: 224
  num_classes: 1000

source_model_architecture:
  name: imagenet_resnet
  image_size: 224
  num_classes: 1000

null_model_architecture:
  name: imagenet_resnet
  image_size: 224
  num_classes: 1000

null_models:
  name: load_null_models_resnet
  paths: ['outputs/imagenet/null_models/00000_null_model/best.pth',
          'outputs/imagenet/null_models/00001_null_model/best.pth',
          'outputs/imagenet/null_models/00002_null_model/best.pth',
          'outputs/imagenet/null_models/00003_null_model/best.pth'
  ]
  num_classes: 1000
  image_size: 224

optimizer:
  name: SGD
  lr: 0.1
  weight_decay: 5.e-4
  momentum: 0.9
  nesterov: true

wm_dataset:
  name: ImageNetDataLoader
  apply_augmentation: False
  subset: all
  shuffle: True
  train: True
  root: ~/.wrt/data
  batch_size: 64
  image_size: 224
  num_workers: 16

dataset:
  name: ImageNetDataLoader
  subset: all
  root: ~/.wrt/data
  batch_size: 64
  image_size: 224
  num_workers: 16

name: deepsignwb
output_dir: outputs/imagenet/decision_thresholds/deepsignwb