wm_scheme:
  name: wm_frontier_stitching
  eps: 0.05
  num_classes: 1000

secret_keys:
  name: wm_frontier_stitching_keygen
  key_expansion_factor: 10
  batch_size: 64
  image_size: 224
  num_classes: 1000

source_model_architecture:
  name: imagenet_resnet
  image_size: 224
  num_classes: 1000

null_models:
  name: load_null_models_imagenet

null_model_architecture:
  help: Determined at runtime

load_pretrained_source_model:
  name: load_pretrained_model
  filename: "outputs/imagenet/wm/frontier_stitching/00000_frontier_stitching/best.pth"

optimizer:
  name: SGD
  lr: 0.1
  weight_decay: 5.e-4
  momentum: 0.9
  nesterov: true

wm_dataset:
  name: ImageNetDataLoader
  apply_normalization: False
  apply_augmentation: False
  subset: all
  train: True
  root: ~/.wrt/data
  batch_size: 64
  image_size: 224
  num_workers: 16

dataset:
  name: ImageNetDataLoader
  subset: all
  root: ~/.wrt/data
  batch_size: 64
  image_size: 224
  num_workers: 16

name: frontier_stitching
output_dir: outputs/imagenet/decision_thresholds/frontier_stitching