wm_scheme:
  name: wm_jia
  snnl_weight: 1
  pos: (0, 100, 100),
  trigger_width: 80
  trigger_height: 80
  num_classes: 1000

source_model_architecture:
  name: imagenet_resnet
  image_size: 224
  num_classes: 1000

null_models:
  name: load_null_models_imagenet

null_model_architecture:
  help: Determined at runtime.

secret_keys:
  name: wm_jia_keygen
  source_class: 3
  target_class: 4
  num_classes: 1000
  image_size: 224

optimizer:
  name: SGD
  lr: 0.1
  weight_decay: 5.e-4
  momentum: 0.9
  nesterov: true

wm_dataset:
  name: ImageNetDataLoader
  apply_normalization: False
  apply_augmentation: False
  train: True
  subset: all
  root: ~/.wrt/data
  batch_size: 64
  image_size: 224
  num_workers: 16

wm_dataset_target:
  name: ImageNetDataLoader
  subset: all
  apply_normalization: False
  apply_augmentation: False
  train: True
  root: ~/.wrt/data
  batch_size: 64
  image_size: 224
  num_workers: 16

dataset:
  name: ImageNetDataLoader
  subset: all
  root: ~/.wrt/data
  batch_size: 64
  image_size: 224
  num_workers: 16

name: jia
output_dir: outputs/imagenet/decision_thresholds/jia