model:
  name: imagenet_resnet
  num_classes: 1000
  image_size: 224

dataset:
  name: ImageNetDataLoader
  subset: all
  root: ~/.wrt/data
  batch_size: 64
  image_size: 224
  num_workers: 16

optimizer:
  name: SGD
  lr: 0.1
  weight_decay: 0.0001
  momentum: 0.9

scheduler:
  name: ReduceLROnPlateau
  factor: 0.1
  patience: 2
  verbose: True

trainer:
  name: Trainer
  num_epochs: 60

name: null_model
output_dir: outputs/imagenet/null_models/